version: '1'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=http://localhost:3000/
    networks:
      - mynetwork

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
